#!/bin/bash

# To be run as root (or started from the SysV init script)
# after setting the DAEMON_FIFO env variable

set -eu

if [ ! -e "$DAEMON_FIFO" ]; then
    # create the fifo with private permissions:
    mkfifo "$DAEMON_FIFO" -m 0600
    # then open up the permissions:
    if [ -n "$DAEMON_FIFO_GROUP" ]; then
	chgrp "$DAEMON_FIFO_GROUP" "$DAEMON_FIFO"
	chmod g+w "$DAEMON_FIFO"
    else
        # allow everyone to write to it:
	chmod go+w "$DAEMON_FIFO"
    fi
fi

while true; do
    cat "$DAEMON_FIFO"  | while read line; do
	echo "$line";
	# run your program from here.
    done
done

