#!/bin/bash

# SysV init script, to be put or symlinked at /etc/init.d/

servicename=my-daemon
pidfile="/var/run/$servicename.pid"
daemon=/opt/my-daemon/daemon  # change to install path

# since the daemon is written as shell script, there is no binary name
# characterizing it, so start-stop-daemon seems to be unable to stop
# it; so instead start it in a new process group (using setsid) and
# kill the process group ourselves:

start () {
    # quote path:
    qdaemon=$(printf '%q' "$daemon")
    qservicename=$(printf '%q' "$servicename")
    # Is the service already running? Test by killing the group, since
    # start-stop-daemon doesn't check correctly:
    if [ -f "$pidfile" ]; then
	if kill -0 -`cat "$pidfile"` 2> /dev/null; then
	    # echo 'still running'
	    return
	fi
    fi
    start-stop-daemon --pidfile "$pidfile" --make-pidfile --background --exec /usr/bin/setsid --start -- bash -c "exec $qdaemon 2>&1 | logger -t $qservicename"
}

stop () {
    if [ -f "$pidfile" ]; then
	for pid in `cat "$pidfile"`; do
	    kill -INT -$pid
	done
	rm -f "$pidfile"
    fi
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    stop
    start
    ;;
    *)
    echo "usage: $0 start|stop|restart"
    exit 1
    ;;
esac

